---
- name: spring-pet-clinic
  hosts: appserver
  become: yes
  tasks:
    - name: apt update and java installation
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Creating  a directory if it does not exist
      ansible.builtin.file:
        path: /usr/share/springpetclinic
        state: directory
    - name: Downloading spring-pet-clinic
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: Adding user
      ansible.builtin.user:
        name: springbootuser
        password: springbootuser
        state: present
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500'
    - name: adding springpetclinic.service file
      ansible.builtin.copy:
        path: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: systemctl enable and start the service
      ansible.builtin.systemd:
        name: springpetclinic.service
        state: started
        enabled: yes
    