---
- name: apache server
  hosts: all
  become: yes
  tasks:
    - name: ubuntu update and apache server installation
      apt:
        name: apache2
        update_cache: yes
        state: present
